@extends('layouts.app')
@section('title')
    Clientes
@endsection
@section('content')
    <gestion-cliente
        :clientes="{{$clientes}}"
        :tipopago="{{$tipoPago}}"
        :tipoidentificacion="{{$tipoIdentificacion}}"
        :paises="{{$paises}}"
    ></gestion-cliente>
@endsection