@extends('layouts.app')
@section('title')
    Perfil
@endsection
@section('content')
    <perfil-component
            :usuario="{{$usuario}}"
            :storage="'{{\Illuminate\Support\Facades\Storage::url('img_user')}}'"
    ></perfil-component>
@endsection